/**
 * withSSLPinning - Expo Config Plugin
 *
 * Android: Creates network_security_config.xml to enforce HTTPS-only
 * traffic and block cleartext requests.
 *
 * iOS: ATS (App Transport Security) already enforces HTTPS by default.
 * True certificate pinning on iOS requires a native URLSession delegate
 * or a library like react-native-ssl-pinning (TODO: Phase 2).
 *
 * Usage in app.json:
 *   "plugins": ["./plugins/withSSLPinning"]
 *
 * What this does:
 * 1. Creates res/xml/network_security_config.xml with:
 *    - Cleartext traffic blocked globally
 *    - Debug overrides so dev builds work (localhost, Metro, etc.)
 *    - Supabase domain pinned to system trust store
 * 2. Adds android:networkSecurityConfig to AndroidManifest.xml
 *
 * TODO Phase 2: Add SPKI certificate pin hashes for the Supabase
 * certificate chain. Requires extracting pins via:
 *   openssl s_client -connect bjkhofdrzpczgnwxoauk.supabase.co:443 \
 *     -servername bjkhofdrzpczgnwxoauk.supabase.co 2>/dev/null \
 *     | openssl x509 -pubkey -noout \
 *     | openssl pkey -pubin -outform der \
 *     | openssl dgst -sha256 -binary \
 *     | openssl enc -base64
 */

const { withAndroidManifest, AndroidConfig } = require('expo/config-plugins');
const { mkdirSync, writeFileSync, existsSync } = require('fs');
const { join } = require('path');

const SUPABASE_HOST = 'bjkhofdrzpczgnwxoauk.supabase.co';

/**
 * Generate network_security_config.xml content
 */
function generateMainNetworkSecurityConfig() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Network Security Configuration - OnSite Timekeeper [RELEASE VARIANT]
  Generated by plugins/withSSLPinning.js (Expo config plugin)

  - Cleartext blocked globally (production-safe)
  - Cleartext exception only for 10.0.2.2 and localhost (Android emulator -> Metro bundler in dev)
  - HTTPS enforced for Supabase domain
  - JS-level fetch interceptor (sslPinning.ts) handles domain validation for all other requests
-->
<network-security-config>
  <!-- Global: cleartext blocked (production safety, MITM protection) -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>

  <!-- Dev only: Metro bundler reachable via 10.0.2.2 (Android emulator) and localhost -->
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">10.0.2.2</domain>
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">127.0.0.1</domain>
  </domain-config>

  <!-- Supabase API: enforce HTTPS only -->
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="true">${SUPABASE_HOST}</domain>
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </domain-config>

  <!-- Debug: trust user-installed certificates (Charles Proxy, etc.) -->
  <debug-overrides>
    <trust-anchors>
      <certificates src="user" />
      <certificates src="system" />
    </trust-anchors>
  </debug-overrides>
</network-security-config>`;
}

function generateDebugNetworkSecurityConfig() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Network Security Configuration - OnSite Timekeeper [DEBUG VARIANT]
  Generated by plugins/withSSLPinning.js (Expo config plugin)

  This file applies ONLY to debug builds (src/debug/ overrides src/main/
  during Android build). Release builds use the main variant which blocks
  cleartext globally.

  Debug needs cleartext enabled because Metro bundler runs on the dev
  machine's LAN IP over plain HTTP when a physical device connects.
-->
<network-security-config>
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
      <certificates src="user" />
    </trust-anchors>
  </base-config>
</network-security-config>`;
}

/**
 * Config plugin: modify Android build to include network security config
 */
function withSSLPinning(config) {
  return withAndroidManifest(config, async (modConfig) => {
    const androidManifest = modConfig.modResults;
    const platformRoot = modConfig.modRequest.platformProjectRoot;

    // 1a. Write main (release) network_security_config.xml
    const mainXmlDir = join(platformRoot, 'app', 'src', 'main', 'res', 'xml');
    if (!existsSync(mainXmlDir)) mkdirSync(mainXmlDir, { recursive: true });
    writeFileSync(
      join(mainXmlDir, 'network_security_config.xml'),
      generateMainNetworkSecurityConfig(),
      'utf-8'
    );

    // 1b. Write debug variant — src/debug/ overrides src/main/ during debug builds.
    // Metro bundler reaches physical devices over the dev machine's LAN IP (plain
    // HTTP), which varies per network. Simplest to allow cleartext globally for
    // debug only; the release config remains locked down.
    const debugXmlDir = join(platformRoot, 'app', 'src', 'debug', 'res', 'xml');
    if (!existsSync(debugXmlDir)) mkdirSync(debugXmlDir, { recursive: true });
    writeFileSync(
      join(debugXmlDir, 'network_security_config.xml'),
      generateDebugNetworkSecurityConfig(),
      'utf-8'
    );

    // 2. Add networkSecurityConfig to <application> in AndroidManifest.xml
    const application = androidManifest.manifest.application?.[0];
    if (application) {
      application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }

    return modConfig;
  });
}

module.exports = withSSLPinning;
