/**
 * withSSLPinning - Expo Config Plugin
 *
 * Android: Creates network_security_config.xml to enforce HTTPS-only
 * traffic and block cleartext requests.
 *
 * iOS: ATS (App Transport Security) already enforces HTTPS by default.
 * True certificate pinning on iOS requires a native URLSession delegate
 * or a library like react-native-ssl-pinning (TODO: Phase 2).
 *
 * Usage in app.json:
 *   "plugins": ["./plugins/withSSLPinning"]
 *
 * What this does:
 * 1. Creates res/xml/network_security_config.xml with:
 *    - Cleartext traffic blocked globally
 *    - Debug overrides so dev builds work (localhost, Metro, etc.)
 *    - Supabase domain pinned to system trust store
 * 2. Adds android:networkSecurityConfig to AndroidManifest.xml
 *
 * TODO Phase 2: Add SPKI certificate pin hashes for the Supabase
 * certificate chain. Requires extracting pins via:
 *   openssl s_client -connect bjkhofdrzpczgnwxoauk.supabase.co:443 \
 *     -servername bjkhofdrzpczgnwxoauk.supabase.co 2>/dev/null \
 *     | openssl x509 -pubkey -noout \
 *     | openssl pkey -pubin -outform der \
 *     | openssl dgst -sha256 -binary \
 *     | openssl enc -base64
 */

const { withAndroidManifest, AndroidConfig } = require('expo/config-plugins');
const { mkdirSync, writeFileSync, existsSync } = require('fs');
const { join } = require('path');

const SUPABASE_HOST = 'bjkhofdrzpczgnwxoauk.supabase.co';

/**
 * Generate network_security_config.xml content
 */
function generateNetworkSecurityConfig() {
  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Network Security Configuration - OnSite Timekeeper
  Generated by plugins/withSSLPinning.js (Expo config plugin)

  - Blocks all cleartext (HTTP) traffic in production
  - Allows localhost/10.0.2.2 in debug builds (Metro bundler)
  - Enforces system trust store for Supabase domain

  TODO Phase 2: Add certificate pins (pin-set) for Supabase domain:
  <pin-set expiration="2027-01-01">
    <pin digest="SHA-256">BASE64_ENCODED_SPKI_HASH_HERE</pin>
    <pin digest="SHA-256">BACKUP_PIN_HERE</pin>
  </pin-set>
-->
<network-security-config>
  <!-- Global: block cleartext traffic -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>

  <!-- Supabase API: system trust store (HTTPS enforced) -->
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="true">${SUPABASE_HOST}</domain>
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </domain-config>

  <!-- Debug overrides: allow Metro bundler + localhost -->
  <debug-overrides>
    <trust-anchors>
      <certificates src="user" />
      <certificates src="system" />
    </trust-anchors>
  </debug-overrides>
</network-security-config>`;
}

/**
 * Config plugin: modify Android build to include network security config
 */
function withSSLPinning(config) {
  return withAndroidManifest(config, async (modConfig) => {
    const androidManifest = modConfig.modResults;

    // 1. Write network_security_config.xml
    const resXmlDir = join(
      modConfig.modRequest.platformProjectRoot,
      'app', 'src', 'main', 'res', 'xml'
    );

    if (!existsSync(resXmlDir)) {
      mkdirSync(resXmlDir, { recursive: true });
    }

    writeFileSync(
      join(resXmlDir, 'network_security_config.xml'),
      generateNetworkSecurityConfig(),
      'utf-8'
    );

    // 2. Add networkSecurityConfig to <application> in AndroidManifest.xml
    const application = androidManifest.manifest.application?.[0];
    if (application) {
      application.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }

    return modConfig;
  });
}

module.exports = withSSLPinning;
